from __future__ import annotations

from astro_viewer.app.models.observing import AstronomicalEvent, CelestialObject, MoonSummary
from astro_viewer.app.services.localization import tr


def mock_planets() -> list[CelestialObject]:
    return [
        CelestialObject(
            id="jupiter",
            name=tr("Giove"),
            object_type=tr("Pianeta"),
            image="resources/images/solar_system/jupiter.jpg",
            magnitude="-2.1",
            distance=tr("760 milioni km"),
            max_altitude=tr("42 gradi"),
            direction=tr("Sud-Est"),
            best_time="23:40",
            observing_window="22:20 - 02:10",
            notes=tr("Bande equatoriali ben contrastate con seeing stabile."),
            recommended_setup=tr("Telescopio medio, oculare 10 mm"),
            visibility_class=tr("Piccolo telescopio"),
            azimuth=tr("142 gradi"),
            time_above_horizon=tr("6 h 40 min"),
        ),
        CelestialObject(
            id="saturn",
            name=tr("Saturno"),
            object_type=tr("Pianeta"),
            image="resources/images/solar_system/saturn.jpg",
            magnitude="0.7",
            distance=tr("1,35 miliardi km"),
            max_altitude=tr("36 gradi"),
            direction=tr("Sud"),
            best_time="01:15",
            observing_window="23:30 - 03:20",
            notes=tr("Anelli visibili a medio ingrandimento; attendere turbolenza bassa."),
            recommended_setup=tr("Telescopio medio, oculare 10 mm o 6 mm"),
            visibility_class=tr("Medio telescopio"),
            azimuth=tr("185 gradi"),
            time_above_horizon=tr("5 h 55 min"),
        ),
        CelestialObject(
            id="venus",
            name=tr("Venere"),
            object_type=tr("Pianeta"),
            image="resources/images/solar_system/venus.jpg",
            magnitude="-3.9",
            distance=tr("118 milioni km"),
            max_altitude=tr("18 gradi"),
            direction=tr("Ovest"),
            best_time="21:30",
            observing_window="20:55 - 22:05",
            notes=tr("Molto luminoso ma basso: osservare con orizzonte libero."),
            recommended_setup=tr("Occhio nudo o piccolo telescopio"),
            visibility_class=tr("Occhio nudo"),
            azimuth=tr("278 gradi"),
            time_above_horizon=tr("1 h 35 min"),
        ),
    ]


def mock_deep_sky() -> list[CelestialObject]:
    return [
        CelestialObject(
            id="m13",
            name=tr("M13 Ercole"),
            object_type=tr("Ammasso globulare"),
            image="resources/images/m13.svg",
            magnitude="5.8",
            distance=tr("22.200 anni luce"),
            max_altitude=tr("74 gradi"),
            direction=tr("Sud"),
            best_time="00:20",
            observing_window="22:15 - 02:50",
            notes=tr("Richiede cielo buio; risoluzione stellare evidente da 150 mm."),
            recommended_setup=tr("Ottimo con oculare da 25 mm, poi 10 mm"),
            visibility_class=tr("Binocolo"),
            azimuth=tr("176 gradi"),
            time_above_horizon=tr("8 h 10 min"),
        ),
        CelestialObject(
            id="m57",
            name=tr("M57 Nebulosa Anello"),
            object_type=tr("Nebulosa planetaria"),
            image="resources/images/m57.svg",
            magnitude="8.8",
            distance=tr("2.570 anni luce"),
            max_altitude=tr("82 gradi"),
            direction=tr("Sud-Est"),
            best_time="01:05",
            observing_window="23:00 - 03:00",
            notes=tr("Compatta e luminosa; filtro UHC utile sotto cieli suburbani."),
            recommended_setup=tr("Telescopio medio, oculare 10 mm"),
            visibility_class=tr("Medio telescopio"),
            azimuth=tr("154 gradi"),
            time_above_horizon=tr("7 h 35 min"),
        ),
        CelestialObject(
            id="albireo",
            name="Albireo",
            object_type=tr("Stella doppia"),
            image="resources/images/albireo.svg",
            magnitude="3.1 / 5.1",
            distance=tr("430 anni luce"),
            max_altitude=tr("67 gradi"),
            direction=tr("Est"),
            best_time="23:55",
            observing_window="22:40 - 02:20",
            notes=tr("Contrasto cromatico oro-blu molto evidente a bassi ingrandimenti."),
            recommended_setup=tr("Piccolo telescopio, oculare 25 mm"),
            visibility_class=tr("Piccolo telescopio"),
            azimuth=tr("118 gradi"),
            time_above_horizon=tr("6 h 25 min"),
        ),
        CelestialObject(
            id="m31",
            name=tr("M31 Andromeda"),
            object_type=tr("Galassia"),
            image="resources/images/m31.svg",
            magnitude="3.4",
            distance=tr("2,54 milioni di anni luce"),
            max_altitude=tr("48 gradi"),
            direction=tr("Nord-Est"),
            best_time="03:10",
            observing_window="01:50 - 04:20",
            notes=tr("Troppo estesa per alti ingrandimenti; preferire cielo buio."),
            recommended_setup=tr("Binocolo 10x50 o oculare 32 mm"),
            visibility_class=tr("Binocolo"),
            azimuth=tr("64 gradi"),
            time_above_horizon=tr("4 h 50 min"),
        ),
    ]


def mock_moon() -> MoonSummary:
    return MoonSummary(
        phase=tr("Crescente"),
        illumination="38%",
        rise_time="12:44",
        set_time="00:38",
        best_note=tr("Terminatore ben definito: filtro lunare consigliato oltre 100 mm."),
        image="resources/images/solar_system/moon.jpg",
    )


def mock_events() -> list[AstronomicalEvent]:
    events = [
        AstronomicalEvent(
            id="new-moon",
            title=tr("Luna nuova"),
            event_type="Luna",
            date_label=tr("10 luglio"),
            best_time=tr("Notte intera"),
            usefulness=98,
            setup=tr("Occhio nudo, binocolo, telescopi"),
            note=tr("Finestra ideale per galassie e nebulose deboli."),
        ),
        AstronomicalEvent(
            id="saturn-opposition",
            title=tr("Saturno in opposizione"),
            event_type="Opposizione",
            date_label=tr("27 settembre"),
            best_time="00:30",
            usefulness=94,
            setup=tr("Telescopio medio o grande"),
            note=tr("Massimo diametro apparente e visibilità prolungata."),
        ),
        AstronomicalEvent(
            id="perseids",
            title=tr("Massimo Perseidi"),
            event_type="Sciame meteorico",
            date_label=tr("12 agosto"),
            best_time="02:00 - 04:30",
            usefulness=86,
            setup=tr("Occhio nudo"),
            note=tr("Scegliere un orizzonte aperto a Nord-Est e un cielo buio."),
        ),
        AstronomicalEvent(
            id="jupiter-visibility",
            title=tr("Giove in massima visibilità serale"),
            event_type=tr("Pianeti"),
            date_label=tr("18 novembre"),
            best_time="23:00",
            usefulness=82,
            setup=tr("Piccolo telescopio"),
            note=tr("Transiti frequenti dei satelliti galileiani."),
        ),
        AstronomicalEvent(
            id="full-moon",
            title=tr("Luna piena"),
            event_type="Luna",
            date_label=tr("24 luglio"),
            best_time="22:15",
            usefulness=45,
            setup=tr("Filtro lunare"),
            note=tr("Buona per i dettagli lunari, sfavorevole per il cielo profondo."),
        ),
        AstronomicalEvent(
            id="future-eclipse",
            title=tr("Eclissi lunare parziale"),
            event_type="Eclissi",
            date_label=tr("7 settembre"),
            best_time="21:35",
            usefulness=76,
            setup=tr("Occhio nudo o teleobiettivo"),
            note=tr("Evento basso sull'orizzonte: verifica gli ostacoli locali."),
        ),
    ]
    return sorted(events, key=lambda event: event.usefulness, reverse=True)
