from __future__ import annotations

from astro_viewer.app.models.observing import AstronomicalEvent, CelestialObject, MoonSummary


def mock_planets() -> list[CelestialObject]:
    return [
        CelestialObject(
            id="jupiter",
            name="Giove",
            object_type="Pianeta",
            image="resources/images/jupiter.svg",
            magnitude="-2.1",
            distance="760 milioni km",
            max_altitude="42 gradi",
            direction="Sud-est",
            best_time="23:40",
            observing_window="22:20 - 02:10",
            notes="Bande equatoriali ben contrastate con seeing stabile.",
            recommended_setup="Telescopio medio, oculare 10 mm",
            visibility_class="Piccolo telescopio",
            azimuth="142 gradi",
            time_above_horizon="6 h 40 min",
        ),
        CelestialObject(
            id="saturn",
            name="Saturno",
            object_type="Pianeta",
            image="resources/images/saturn.svg",
            magnitude="0.7",
            distance="1.35 miliardi km",
            max_altitude="36 gradi",
            direction="Sud",
            best_time="01:15",
            observing_window="23:30 - 03:20",
            notes="Anelli visibili a medio ingrandimento; attendere turbolenza bassa.",
            recommended_setup="Telescopio medio, oculare 10 mm o 6 mm",
            visibility_class="Medio telescopio",
            azimuth="185 gradi",
            time_above_horizon="5 h 55 min",
        ),
        CelestialObject(
            id="venus",
            name="Venere",
            object_type="Pianeta",
            image="resources/images/venus.svg",
            magnitude="-3.9",
            distance="118 milioni km",
            max_altitude="18 gradi",
            direction="Ovest",
            best_time="21:30",
            observing_window="20:55 - 22:05",
            notes="Molto luminoso ma basso: osservare con orizzonte libero.",
            recommended_setup="Occhio nudo o piccolo telescopio",
            visibility_class="Occhio nudo",
            azimuth="278 gradi",
            time_above_horizon="1 h 35 min",
        ),
    ]


def mock_deep_sky() -> list[CelestialObject]:
    return [
        CelestialObject(
            id="m13",
            name="M13 Ercole",
            object_type="Ammasso globulare",
            image="resources/images/m13.svg",
            magnitude="5.8",
            distance="22.200 anni luce",
            max_altitude="74 gradi",
            direction="Sud",
            best_time="00:20",
            observing_window="22:15 - 02:50",
            notes="Richiede cielo buio; risoluzione stellare evidente da 150 mm.",
            recommended_setup="Ottimo con oculare da 25 mm, poi 10 mm",
            visibility_class="Binocolo",
            azimuth="176 gradi",
            time_above_horizon="8 h 10 min",
        ),
        CelestialObject(
            id="m57",
            name="M57 Nebulosa Anello",
            object_type="Nebulosa planetaria",
            image="resources/images/m57.svg",
            magnitude="8.8",
            distance="2.570 anni luce",
            max_altitude="82 gradi",
            direction="Sud-est",
            best_time="01:05",
            observing_window="23:00 - 03:00",
            notes="Compatta e luminosa; filtro UHC utile sotto cieli suburbani.",
            recommended_setup="Telescopio medio, oculare 10 mm",
            visibility_class="Medio telescopio",
            azimuth="154 gradi",
            time_above_horizon="7 h 35 min",
        ),
        CelestialObject(
            id="albireo",
            name="Albireo",
            object_type="Stella doppia",
            image="resources/images/albireo.svg",
            magnitude="3.1 / 5.1",
            distance="430 anni luce",
            max_altitude="67 gradi",
            direction="Est",
            best_time="23:55",
            observing_window="22:40 - 02:20",
            notes="Contrasto cromatico oro-blu molto evidente a bassi ingrandimenti.",
            recommended_setup="Piccolo telescopio, oculare 25 mm",
            visibility_class="Piccolo telescopio",
            azimuth="118 gradi",
            time_above_horizon="6 h 25 min",
        ),
        CelestialObject(
            id="m31",
            name="M31 Andromeda",
            object_type="Galassia",
            image="resources/images/m31.svg",
            magnitude="3.4",
            distance="2.54 milioni anni luce",
            max_altitude="48 gradi",
            direction="Nord-est",
            best_time="03:10",
            observing_window="01:50 - 04:20",
            notes="Troppo estesa per alti ingrandimenti; preferire cielo buio.",
            recommended_setup="Binocolo 10x50 o oculare 32 mm",
            visibility_class="Binocolo",
            azimuth="64 gradi",
            time_above_horizon="4 h 50 min",
        ),
    ]


def mock_moon() -> MoonSummary:
    return MoonSummary(
        phase="Crescente",
        illumination="38%",
        rise_time="12:44",
        set_time="00:38",
        best_note="Terminator ben definito: consigliato filtro lunare oltre 100 mm.",
        image="resources/images/moon.svg",
    )


def mock_events() -> list[AstronomicalEvent]:
    events = [
        AstronomicalEvent(
            id="new-moon",
            title="Luna nuova",
            event_type="Luna",
            date_label="10 luglio",
            best_time="Notte intera",
            usefulness=98,
            setup="Occhio nudo, binocolo, telescopi",
            note="Finestra ideale per galassie e nebulose deboli.",
        ),
        AstronomicalEvent(
            id="saturn-opposition",
            title="Saturno in opposizione",
            event_type="Opposizione",
            date_label="27 settembre",
            best_time="00:30",
            usefulness=94,
            setup="Telescopio medio o grande",
            note="Massimo diametro apparente e visibilità prolungata.",
        ),
        AstronomicalEvent(
            id="perseids",
            title="Massimo Perseidi",
            event_type="Sciame meteorico",
            date_label="12 agosto",
            best_time="02:00 - 04:30",
            usefulness=86,
            setup="Occhio nudo",
            note="Scegliere orizzonte nord-est aperto e cielo scuro.",
        ),
        AstronomicalEvent(
            id="jupiter-visibility",
            title="Giove in massima visibilità serale",
            event_type="Pianeti",
            date_label="18 novembre",
            best_time="23:00",
            usefulness=82,
            setup="Piccolo telescopio",
            note="Transiti dei satelliti galileiani frequenti.",
        ),
        AstronomicalEvent(
            id="full-moon",
            title="Luna piena",
            event_type="Luna",
            date_label="24 luglio",
            best_time="22:15",
            usefulness=45,
            setup="Filtro lunare",
            note="Buona per dettagli lunari, sfavorevole per cielo profondo.",
        ),
        AstronomicalEvent(
            id="future-eclipse",
            title="Eclissi lunare parziale",
            event_type="Eclissi",
            date_label="7 settembre",
            best_time="21:35",
            usefulness=76,
            setup="Occhio nudo o teleobiettivo",
            note="Evento basso sull'orizzonte: verificare ostacoli locali.",
        ),
    ]
    return sorted(events, key=lambda event: event.usefulness, reverse=True)
